### PR TITLE
bugfix: update claimable FOX rewards when account is switched (Issue 37)

### LINKED ISSUE #37: Change account using MetaMask doesn't update claimable FOX
Description: When a user changes accounts on MetaMask, all amounts update except for the FOX Rewards available for claiming.

Steps to reproduce:

Visit https://fox.shapeshift.com/airdrop
Connect MetaMask Wallet
View claimable FOX rewards on initial account
Switch to other MetaMask Account
Notice all values update except for the claimable FOX amount which stays the same as the previous account

### PR DESCRIPTION
**Pull request by millsmcilroy**
closes #37

### CODE REVIEW

File: src/pages/Farm/RewardAmounts.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ export const RewardAmounts = ({ foxAmount }: TRewardAmounts) => {
         <>
           <Text color='gray.500'>Available Rewards</Text>
           <Text fontSize='5xl' fontWeight='bold' mt='-10px' mb='-5px'>
-            ${fiatAmount}
+            ${fiatAmount || '0.00'}
```
Comment (millsmcilroy) [inline src/pages/Farm/RewardAmounts.tsx:34]: fiatAmount was an empty string when there where no available rewards

**Review by Lazymondaysunday — APPROVED** [review]

**Review by unclerom — APPROVED** [review]

File: src/pages/Farm/RewardAmounts.tsx (hunk 1 above)
Comment (unclerom) [reply src/pages/Farm/RewardAmounts.tsx:34]: I believe the idea for it to be blank was based on the fact that the `useCoinCapPrice` hook could fail to get the price but we would still be able to show their fox amount without the user seeing $0 and getting nervous

Comment (unclerom) [reply src/pages/Farm/RewardAmounts.tsx:34]: to your point though maybe the `useRealTimeRewardAmounts` hook should return 0 as long as there is a price

**Review by bootsboogie — APPROVED** [review]
